strength/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include ("train.urls"))
]

train/urls.py
"""URL patterns for Personal Training App"""
from django.urls import path
from . import views

urlpatterns = [
    path("",views.home,name="home"),
    path("contact",views.contact,name="contact"),
    path("index", views.index, name="index"),
        path("events",views.events,name="event"),
        path("<int:pnum>", views.index, name="index"),
        path("login", views.login_view, name="login"),
        path("logout", views.logout_view, name="logout"),
        path("register", views.register, name="register"),
        path("newsession", views.newsession, name="newsession"),
        path("newsession/<int:pk>", views.sessionview, name="sessionview"),
        path("editsession", views.editsession, name="editsession"),
        path("editsession/<int:session>", views.editsession, name="editsession"),
        path("routines/new", views.newroutine, name="newroutine"),
        path("routines/edit", views.routinelist, name="routinelist"),
        path("routines/edit/<int:pk>", views.editroutine, name="editroutine"),
        path("exercises", views.exerciseview, name="exerciseview"),
        path("charts", views.charts, name="charts"),
        path("charts/<int:pnum>", views.charts, name="charts"),

        path("clientroutines", views.clientroutines, name="clientroutines"),
        path("clientroutines/<int:pnum>", views.clientroutines, name="clientroutines"),
        path("clientprogress", views.clientprogress, name="clientprogress"),

        path("postset", views.postset, name="postset"),
        path("setgroupinfo", views.setgroupinfo, name="setgroupinfo"),
        path("deletex", views.deletex, name="deletex"),
        path("deletesession/<int:sessionpk>", views.deletesession, name="deletesession"),
        path("checkcomplete/<int:sessionpk>", views.checkcomplete, name="checkcomplete"),
        path("deleteempties/<int:sessionpk>", views.deleteempties, name="deleteempties"),
        path("fetchsessions/<int:client>", views.fetchsessions, name="fetchsessions"),
        path("updateset", views.updateset, name="updateset"),
        path("archive/<int:routine>", views.archive, name="archive"),
        path("anotherexercise", views.anotherexercise, name="anotherexercise"),
        path("progressAPI/<int:exercise>", views.progressAPI, name="progressAPI")
]

train/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Client, Trainer, or Admin user"""
    user_choices = [('CL', 'client'), ('TR', 'trainer'), ('AD', 'admin')]
    subscription = models.CharField(max_length=2,null=False)
    def __str__(self):
        return f"{self.first_name}"

class Exercise(models.Model):
    """Exercise such as plank, squat, row"""
    body_choices = [
        ('LE', 'Legs'),
        ('AR', 'Arms'),
        ('BA', 'Back'),
        ('CH', 'Chest'),
        ('SH', 'Shoulders'),
        ('CO', 'Core'),
        ('OT', 'Other')
    ]
    name = models.CharField(max_length=40, unique=True)
    body_part = models.CharField(max_length=2, choices=body_choices)

    def __str__(self):
        return self.name

class Routine(models.Model):
    """A group of exercises for a particular user"""
    name = models.CharField(max_length=20, verbose_name='Routine Name')
    startdate = models.DateField(auto_now_add=True)
    client = models.ForeignKey("User", on_delete=models.CASCADE, related_name="routines",
                              limit_choices_to={'is_staff': 'False'})
    exercises = models.ManyToManyField("Exercise", related_name="routines")
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.client.first_name}'s {self.name}"

class Setgroup(models.Model):
    """Series of sets for a specicic excercise in a specific routine"""
    exercise = models.ForeignKey("Exercise", on_delete=models.PROTECT, related_name="setgroups")
    session = models.ForeignKey("Session", on_delete=models.CASCADE, related_name="setgroups")
    note = models.CharField(max_length=50, blank=True, null=True)
    order = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f"{self.exercise.name} Sets"

class Set(models.Model):
    """One set of an exercise performed by one user one time"""
    num_choices = [
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5")
    ]
    setgroup = models.ForeignKey("Setgroup", on_delete=models.CASCADE, related_name="sets")
    setnum = models.IntegerField(choices=num_choices, verbose_name='Set')
    weight = models.CharField(max_length=20)
    time = models.CharField(max_length=15)

    def __str__(self):
        return f"set {self.setnum} of {self.setgroup.exercise.name}"

    def serialize(self):
        """serialize Sets for API request"""
        return {
            "date": self.setgroup.session.timestamp.astimezone().strftime("%b %-d %Y, %-I:%M %p"),
            "weight": self.weight,
            "time": self.time
        }

class Session(models.Model):
    """A collection of setgroups by a user on a given day (e.g. a workout)"""
    routine = models.ForeignKey("Routine", on_delete=models.PROTECT, related_name="sessions",
                                limit_choices_to={'archived': 'False'})
    timestamp = models.DateTimeField(auto_now_add=True)
    trainer = models.ForeignKey("User", on_delete=models.SET_NULL, null=True,
                                limit_choices_to={'is_staff': 'True', 'is_superuser': 'False'})

    def __str__(self):
        return f"Session {self.pk} by {self.trainer.first_name} - {self.routine.name}"

    def serialize(self):
        """serialize Sessions for API request"""
        return {
            "pk": self.pk,
            "trainer": self.trainer.first_name,
            "client": self.routine.client.first_name,
            "routine": self.routine.name,
            "timestamp": self.timestamp.astimezone().strftime("%b %-d %Y, %-I:%M %p")
        }

train/forms.py
"""all forms for Train app"""
from django.forms import ModelForm, Select, TextInput, ModelChoiceField, ModelMultipleChoiceField, CheckboxSelectMultiple

from .models import Exercise, Routine, Session, User

class SessionForm(ModelForm):
    """Create new workout session"""
    class Meta:
        model = Session
        fields = ('routine', 'trainer')
        widgets = {
            'routine': Select(attrs={'class': 'form-control'}),
            'trainer': Select(attrs={'class': 'form-control'})
        }

class ExerciseForm(ModelForm):
    """Create a new Exercise"""
    class Meta:
        model = Exercise
        fields = ('name', 'body_part')
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'body_part': Select(attrs={'class': 'form-control'})
        }

class RoutineForm(ModelForm):
    """Create a new Routine"""
    # only client users are options for this form
    client = ModelChoiceField(
            queryset=User.objects.filter(is_staff=False),
            widget=Select(attrs={'class': 'form-control'})
    )
    # exercises need to be pre-orderd by body part for form
    exercises = ModelMultipleChoiceField(
        queryset=Exercise.objects.order_by('body_part')
    )
    class Meta:
        model = Routine
        fields = ('name', 'client', 'exercises')
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
        }

train/views.py
"""Views for Personal Training App"""
import json
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator

from .models import User, Session, Setgroup, Set, Exercise, Routine
from .forms import SessionForm, ExerciseForm, RoutineForm

def home(request):
    data=User.objects.filter(is_staff=True)
    exerciselist = Exercise.objects.all().order_by('name')
    context={'trainer':data,
             'list':exerciselist
             }

    return render(request,"train/index1.html",context)

def contact(request):
    return render(request,"train/contact.html")

def events(request):
    return render(request,"train/events.html")

@login_required
def index(request, pnum=1):
    """Home page only visible if user logged in"""
    # if user is staff, return all workouts
    if request.user.is_staff:
        sessions = Session.objects.all().order_by('-pk')
    else:
        # if user is client, return all workouts for this client
        sessions = Session.objects.filter(routine__client=request.user).order_by('-pk')
    # helper function below: return queryset list of 10
    data = pagehelper(sessions, pnum)
    return render(request, "train/index.html", {
        "data": data
    })

def login_view(request):
    """login view for non-authenticated users"""
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect("index")
        else:
            return render(request, "train/login.html", {
                "message": "Invalid username and/or password."
            })

    # GET request method: display login form
    return render(request, "train/login.html")

def logout_view(request):
    """log out"""
    logout(request)
    return redirect("home")

def register(request):
    """register a new User"""
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        first = request.POST["first"]
        last = request.POST["last"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "train/register.html", {
                "message": "Passwords must match."
            })
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password,
                                            first_name=first, last_name=last)
            user.subsciption=request.POST["pay"]
            user.save()
        except IntegrityError:
            return render(request, "train/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return redirect("index")
    # else request method GET
    return render(request, "train/register.html")

@staff_member_required(login_url="/login")
def newsession(request):
    """Trainer starts a new workout session"""
    # request method POST, create new workout session
    if request.method == "POST":
        form = SessionForm(request.POST)
        if form.is_valid:
            session = form.save()
            # create new Setgroup for each exercise in this routine
            allexercises = session.routine.exercises.all()
            for exercise in allexercises:
                Setgroup.objects.create(exercise=exercise, session=session)
            pk = session.pk
            return redirect("sessionview", pk=pk)

        # if invalid form - return form to user
        return render(request, "train/newsession.html", {
            "form": form
        })
    # if request method is GET, display form
    sessionform = SessionForm()
    return render(request, "train/newsession.html", {
        'form': sessionform
    })

@staff_member_required(login_url="/login")
def sessionview(request, pk):
    """A form to create sets for a specific workout session"""
    try:
        session = Session.objects.get(pk=pk)
    except Session.DoesNotExist:
        # if requested session doesn't exist, return error message
        return render(request, "train/error.html", {
            "message": "That workout session does not exist."
        })
    # all sets for each Setgroup
    setgroups = Setgroup.objects.filter(session=session)

    # if sets have already been logged for this session, redirect to EDIT page
    for group in setgroups:
        if Set.objects.filter(setgroup=group):
            request.session['sessionpk'] = pk
            return redirect("editsession")

    # if previous session using this routine exists, include
    try:
        prevsession = session.get_previous_by_timestamp(routine=session.routine)
    except Session.DoesNotExist:
        prevsession = None
    # exclude all the exercises that already have setgroups added to this Session
    exercises = Exercise.objects.exclude(setgroups__in=(Setgroup.objects.filter(session=session)))

    return render(request, "train/newsession2.html", {
        "setgroups": setgroups,
        "n": range(1, 4),
        "prevsession": prevsession,
        "session": session,
        "exercises": exercises
    })

@staff_member_required(login_url="/login")
def editsession(request):
    """Edit a previously logged session"""
    # if request method GET with session selected (either from template or newsession redirect)
    if 'sessionpk' in request.session or 'sessionpk' in request.GET:
        pk = request.GET.get('sessionpk', False) or request.session['sessionpk']
        # clear this value from the session so not passed to future pages
        if 'sessionpk' in request.session:
            del request.session['sessionpk']
        # get the Session instance from request
        try:
            session = Session.objects.get(pk=pk)
        except Session.DoesNotExist:
            return render(request, "train/error.html", {
                "message": "That workout session does not exist."
            })
        # exclude all the exercises that already have setgroups associated w this Session
        exercises = Exercise.objects.exclude(setgroups__in=(
                    Setgroup.objects.filter(session=session)))

        return render(request, "train/editsession2.html", {
            "session": session,
            "exercises": exercises
        })
    # if request method GET and no session selected
    clients = User.objects.filter(is_staff=False)
    return render(request, "train/editsession1.html", {
        "clients": clients
    })

@staff_member_required(login_url="/login")
def newroutine(request):
    """Create a new Routine"""
    if request.method == "POST":
        form = RoutineForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("routinelist")
        # if invalid form, return to user
        return render(request, "train/newroutine.html", {
            "form": form
        })
    # if request method GET
    form = RoutineForm()
    return render(request, "train/newroutine.html", {
        "form": form
    })

@staff_member_required(login_url="/login")
def routinelist(request):
    """Page that shows list of all routines"""
    routines = Routine.objects.all().order_by('-pk')
    return render(request, "train/routinelist.html", {
        "routines": routines
    })

@staff_member_required(login_url="/login")
def editroutine(request, pk):
    """Update a specific routine that's already been created"""
    if request.method == "POST":
        routine = Routine.objects.get(pk=pk)
        form = RoutineForm(request.POST, instance=routine)
        if form.is_valid():
            form.save()
            return redirect("routinelist")
        # if invalid form: return form to user
        return render(request, "train/editroutine.html", {
            "form": form,
            "routine": routine
        })
    # if GET request, prefill RoutineForm with previously saved info
    routine = Routine.objects.get(pk=pk)
    form = RoutineForm(instance=routine)
    # request method GET: show pre-filled routine form
    return render(request, "train/editroutine.html", {
        "form": form,
        "routine": routine
    })

@staff_member_required(login_url="/login")
def exerciseview(request):
    """Add a new exercise"""
    exerciselist = Exercise.objects.all().order_by('name')
    if request.method == "POST":
        form = ExerciseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("exerciseview")

        # if invalid form - return form to user
        return render(request, "train/exercises.html", {
            "form": form,
            "exerciselist": exerciselist
        })
    # else if request method GET
    form = ExerciseForm()
    return render(request, "train/exercises.html", {
        'form': form,
        "exerciselist": exerciselist
    })

@staff_member_required(login_url="/login")
def charts(request, pnum=1):
    """Display all previous sessions for any client"""
    users = User.objects.filter(is_staff=False)
    # hidden page number from pagination form, if exists
    if 'pnum' in request.GET:
        pnum = int(request.GET['pnum'])
    # if a specific client was selected from dropdown
    if 'client' in request.GET:
        client = request.GET['client']
        client = User.objects.get(pk=client)

train/templates/train/charts.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
    Charts
{% endblock %}
<!--Trainer view: form to show all charts for any selected client-->
{% block body %}
    <div class="container">

        <div class="container select-box">
            <form url="{% url 'charts' %}" id="select-form">
                <div class="form-group row">
                    <select class="custom-select" id="client-select" name="client">
                        <option selected="true" disabled>Select Client</option>
                        {% for user in users %}
                            <option value="{{user.pk}}">{{user.first_name}} {{user.last_name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </form>
        </div>

    {% include "train/charttemplate.html" %}
    {% include "train/paginate-charts.html" %}
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'train/charts.js' %}"></script>
{% endblock %}

train/templates/train/charttemplate.html
{% load static %}
<!--default template to display workout Sessions on any page of this app-->

<!--Div for each Workout Session-->
{% for session in data.sessions %}
    <div class="card container session-card">
        <div class="row card-header">
            <div class="col">
                Client: {{ session.routine.client }} <br>
                Trainer: {{ session.trainer }} <br>
                Routine: {{ session.routine }} <br>
                Time: {{ session.timestamp }} <br>
                Session #{{ session.pk }}
            </div>
            <div class="col">
                {% if user.is_staff %}
                    <form action="{% url 'editsession' %}" method="get">
                        <input hidden name="sessionpk" value="{{session.pk}}">
                        <input type="submit" class="float-right btn btn-sm btn-outline-danger" value="Edit">
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="row card-body">
            {% for group in session.setgroups.all %}
                <div class="col-6 exercise-div">
                    <span class="group-title">
                        {% if group.order %}
                            {{ group.order }} .
                        {% endif %}
                        {{ group }}
                    </span><br>
                    {% if group.note %}
                        <i>Note: {{ group.note }}</i>
                    {% endif %}
                    {% for set in group.sets.all %}
                        <div>
                            Set {{ set.setnum }}: {{ set.weight }} for {{ set.time }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endfor %}

train/templates/train/clientprogress.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
    Progress
{% endblock %}
<!--Client view: list of all exercises ever performed, clicking shows history of sets-->
{% block body %}
    <div class="container">
        <div class="set-group">
            <h3>Exercises</h3>
            {% for exercise in exercises %}
                <div class="fake-link" data-exercise="{{exercise.pk}}">
                    <span class="group-title">{{ exercise }}</span>
                </div>
                <div class="popdown" id="popdown-{{exercise.pk}}"></div>
            {% endfor%}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'train/clientprogress.js' %}"></script>
{% endblock %}

train/templates/train/clientroutines.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
    Charts
{% endblock %}
<!--Client view: See all past workout Sessions for a selected Routine-->
{% block body %}
    <div class="container">
        <!--Select dropdown-->
        <div class="container select-box">
            <form url="{% url 'clientroutines' %}" id="select-form">
                {% csrf_token %}
                <div class="form-group row">
                    <select class="custom-select" id="client-select" name="routine">
                        <option selected="true" disabled>Select Routine</option>
                        {% for routine in routines %}
                            <option value="{{routine.pk}}">{{routine}}</option>
                        {% endfor %}
                    </select>
                </div>
            </form>
        </div>
    <!--A selected Routine with exercises-->
    {% if routineobj %}
            <div class="container set-group">
                <div class="row">
                    <div class="col">
                        <span class="group-title">Name: </span>{{routineobj.name}}<br>
                        <span class="group-title">Started: </span>{{routineobj.startdate}}<br>
                    </div>
                    <div class="col">
                        <span class="group-title">Exercises: </span>
                        {% for exercise in routineobj.exercises.all %}
                            <br>
                            {{ exercise }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    <!--Sessions-->
    {% include "train/charttemplate.html" %}
    {% include "train/paginate-client.html" %}

    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'train/charts.js' %}"></script>
{% endblock %}

train/templates/train/editsession1.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
    Edit Session
{% endblock %}

<!--Page 1 of Edit Session: Trainer view to select a client and Session to edit-->
{% block body %}
<div class="container">
    <div class="set-group">
        <h3> Edit a Previous Session </h3>
        <form action="{% url 'editsession' %}" method="get">
            <div class="form-group">
                <select name="client" id="client-select" class="form-control">
                    <option selected="selected" disabled>Select a Client</option>
                    {% for client in clients %}
                        <option value="{{client.pk}}">{{client.first_name}} {{client.last_name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group" id="session-form">
                <select name="sessionpk" id="session-select" class="form-control">
                    <option selected="selected" disabled>Select a Session</option>
                </select>
                <br>
                <input type="submit" class="btn btn-danger" value="Submit">
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
    <script src="{% static 'train/editsession1.js' %}"></script>
{% endblock %}

train/templates/train/error.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
    Error
{% endblock %}
<!--Error page: shown when a user attempts to access any unauthorized resource-->
{% block body %}
    <div class="container">
        <div class="error">
            Sorry, something went wrong.
                {% if message %}
                    {{ message }}
                {% endif %}
            <br>
            <a class="red-link" href="{% url 'index' %}">Go Home</a>
            
        </div>
    </div>
{% endblock %}

train/templates/train/exercises.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
    Create Exercise
{% endblock %}
<!--Trainer view: create/delete exercises-->
{% block body %}
    <div class="container">
        <!--New Exercise Form-->
        <div class="set-group">
            <h3>Create a New Exercise</h3>
            <form action="{% url 'exerciseview' %}" method="post">
                {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-danger" value="Create">
            </form>
        </div>
        <!--Table of all existing exercises-->
        <div class="set-group">
            <div class="row">
                <div class="col">
                    <h3>All Exercises</h3>
                </div>
                <div class="col">
                    <i>Exercises cannot be deleted once used in a Routine</i>
                </div>
            </div>
            <table class="table table-hover">
                <tr>
                    <th>Exercise</th>
                    <th>Body Part</th>
                    <th></th>
                </tr>
                {% for exercise in exerciselist %}
                    <tr id="row-{{ exercise.pk }}">
                        <td>{{ exercise.name }}</td>
                        <td>{{ exercise.get_body_part_display }} </td>
                            <!--Not sure why this logic works and not the reverse, but button 
                                should be disabled if exercise already exists in routine-->
                            {% if exercise.routines.all %}
                                <td> <button hidden class="delete btn btn-sm btn-outline-danger"></button></td>
                            {% else %}
                                <td> <button data-exercise="{{exercise.pk}}" class="delete btn btn-sm btn-outline-danger">
                                    Delete</button></td>
                            {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static "train/exercises.js" %}"></script>
{% endblock %}

train/templates/train/index.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
All Sessions
{% endblock %}
<!--Home page for both trainers and clients-->
{% block body %}

<div class="container">
    {% include "train/charttemplate.html" %}
    {% include "train/pagetemplate.html" %}
</div>

{% endblock %}

train/templates/train/newroutine.html
{% extends "train/layout.html" %}
{% load static %}


{% block title %}
    Routines
{% endblock %}
<!--Trainer view: form to create a new Routine-->
{% block body %}
    <div class="container">
        <div class="set-group">
            <h3>Create a New Routine</h3>
            <form action="{% url 'newroutine' %}" method="post">
                {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        {{form.name.errors}}
                        {{form.name.label}}
                        {{form.name}}
                    </div>
                    <div class="form-group">
                        {{form.client.errors}}
                        {{form.client.label}}
                        {{form.client}}
                    </div>
                    <hr>
                    <div class="form-group">
                        <h5>Exercises</h5>
                        <div class="row">
                            {{form.exercises.errors}}
                        </div>
                        <div class="row">
                            {% regroup form.fields.exercises.queryset by get_body_part_display as body_list %}
                            {% for body_part in body_list %}
                                <div class="col-6 col-sm-4">
                                    <h6 class="red-link">{{ body_part.grouper }}</h6>
                                    {% for exercise in body_part.list %}
                                        <div class="form-check">
                                            <input type="checkbox" name="exercises" value="{{exercise.pk}}" /> {{exercise}}
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                <input type="submit" class="btn btn-danger float-right" value="Create">
            </form>
        </div>
    </div>
{% endblock %}

train/templates/train/newsession.html
{% extends "train/layout.html" %}
{% load static %}

{% block title %}
New Session
{% endblock %}
<!--Trainer view: start a new workout Session (clicking Create takes you to newsession2.html)-->
{% block body %}
    <div class="container">
        <div class="set-group">
            <h3> Start A New Workout Session</h3>
            <form action="{% url 'newsession' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-danger" value="Create">
            </form>
        </div>
    </div>
{% endblock %}

train/templates/train/pagetemplate.html
{% load static %}

<!--Pagination navigation for INDEX/ default views (trainer and client)-->
<nav aria-label="Page navigation">
    <ul class="pagination pag-align float-right">
        {% if data.prev_page > 0 %}
            <li class="page-item">
                <a class="page-link" href="{% url 'index' pnum=data.prev_page %}">Previous</a></li>
        {% else %}
            <!-- disabled previous button if page 1 -->
            <li class="page-item disabled">
                <span class="page-link">Previous</span></li>
        {% endif %}
            <li class="page-item active" aria-current="page">
                <span class="page-link"> {{ data.pnum }} </span></li>
        {% if data.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'index' pnum=data.next_page %}">Next</a></li>
        {% else %}
            <!-- disabled next button if last page -->
            <li class="page-item disabled">
                <span class="page-link">Next</span></li>
        {% endif %}
    </ul>
</nav>